version: "3.9"
services:
  postgres:
    container_name: assets-service-database
    image: postgres
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_MULTIPLE_DATABASES: "${DATABASE_NAME_PREFIX}_assets_shard_1,${DATABASE_NAME_PREFIX}_assets_shard_2,${DATABASE_NAME_PREFIX}_unsharded"
    volumes:
      - ./scripts/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - database-volume:/var/lib/postgresql/data

  liquibase_assets_shard_1:
    image: liquibase/liquibase
    volumes:
      - ./docker/liquibase/migrations/sharded/assets:/liquibase/changelog
    command:
     - /bin/sh
     - -c
     - |
        echo "sleep 5s"
        sleep 5
        liquibase --username=${DATABASE_USER} --password=${DATABASE_PASSWORD} --changeLogFile=changelog/db.changelog-root.xml --url=${DATABASE_URL}_assets_shard_1 update
    depends_on:
      - postgres
    restart: on-failure
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  liquibase_assets_shard_2:
    image: liquibase/liquibase
    volumes:
      - ./docker/liquibase/migrations/sharded/assets:/liquibase/changelog
    command:
     - /bin/sh
     - -c
     - |
        echo "sleep 5s"
        sleep 5
        liquibase --username=${DATABASE_USER} --password=${DATABASE_PASSWORD} --changeLogFile=changelog/db.changelog-root.xml --url=${DATABASE_URL}_assets_shard_2 update
    depends_on:
      - postgres
    restart: on-failure
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  liquibase_unsharded:
    image: liquibase/liquibase
    volumes:
      - ./docker/liquibase/migrations/unsharded:/liquibase/changelog
    command:
     - /bin/sh
     - -c
     - |
        echo "sleep 5s"
        sleep 5
        liquibase --username=${DATABASE_USER} --password=${DATABASE_PASSWORD} --changeLogFile=changelog/db.changelog-root.xml --url=${DATABASE_URL}_unsharded update
    depends_on:
      - postgres
    restart: on-failure
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  api:
    build: .
    container_name: assets-service-api
    ports:
      - "3005:3005"
    depends_on:
      - liquibase_assets_shard_1
      - liquibase_assets_shard_2
      - liquibase_unsharded
      - postgres
    restart: always
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  database-volume:
networks:
  default:
    name: clearway-task-assets-service-network
