basePath: /
consumes:
    - application/json
definitions:
    AppInfo:
        description: Used rendering cumulative information about the readiness and performance of the service
        x-go-package: github.com/ArtemVoronov/clearway-task-assets-service
    Credentials:
        description: '# Used for authenication and creating users'
        title: Credentails represents the login and password pair
        x-go-package: github.com/ArtemVoronov/clearway-task-assets-service/internal/api/rest/v1
host: https://localhost:3005
info:
    title: 'Assets Service:'
    version: "1.0"
paths:
    /api/users:
        post:
            consumes:
                - application/json
            operationId: createUser
            produces:
                - application/json
            summary: Creates an user
produces:
    - application/json
schemes:
    - https
securityDefinitions:
    Bearer:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
